# Generated by Django 2.1.7 on 2019-03-23 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 0, 38, 708373, tzinfo=utc))),
                ('code', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
