# Generated by Django 2.1.7 on 2019-05-23 15:32

from django.db import migrations

def populateGuidanceCounselorAccounts(apps, schema_editor):
    User = apps.get_model('openapp', 'User')
    
    scs = User(username='scs', password='scs')
    scs.save()

    ced = User(username='ced', password='ced')
    ced.save()

    coet = User(username='coet', password='coet')
    coet.save()

    csm = User(username='csm', password='csm')
    csm.save()

    cbaa = User(username='cbaa', password='cbaa')
    cbaa.save()

    con = User(username='con', password='con')
    con.save()

    con = User(username='con', password='con')
    con.save()

class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0001_initial.py')
    ]

    operations = [
        migrations.RunPython(populateGuidanceCounselorAccounts),
    ]
