# Generated by Django 2.1.7 on 2019-03-23 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 21, 51, 827355, tzinfo=utc))),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 17, 21, 51, 814348, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='anonuser',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openapp.Code'),
        ),
    ]
