# Generated by Django 2.1.7 on 2019-05-23 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('question1', models.CharField(default='', max_length=1000, null=True)),
                ('question2', models.CharField(default='', max_length=1000, null=True)),
                ('question3', models.CharField(default='', max_length=1000, null=True)),
                ('question4', models.CharField(default='', max_length=1000, null=True)),
                ('question5', models.CharField(default='', max_length=1000, null=True)),
                ('question6', models.CharField(default='', max_length=1000, null=True)),
                ('question7', models.CharField(default='', max_length=1000, null=True)),
                ('question8', models.CharField(default='', max_length=1000, null=True)),
                ('question9', models.CharField(default='', max_length=1000, null=True)),
                ('question10', models.CharField(default='', max_length=1000, null=True)),
                ('question11', models.CharField(default='', max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 15, 58, 23, 52238, tzinfo=utc))),
                ('code', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.CharField(max_length=1000)),
                ('seen', models.CharField(default='UNSEEN', max_length=1000)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('notifType', models.CharField(default=None, max_length=1000, null=True)),
                ('notifId', models.CharField(default=None, max_length=1000, null=True)),
                ('status', models.CharField(default=None, max_length=1000, null=True)),
                ('message', models.CharField(default=None, max_length=1000, null=True)),
                ('destUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destUser', to=settings.AUTH_USER_MODEL)),
                ('sourceUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(blank=True, default='', max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.CharField(default=None, max_length=1000)),
                ('status', models.CharField(default=None, max_length=1000)),
                ('approved', models.CharField(blank=True, default='NOT_APPROVED', max_length=1000)),
                ('info_name', models.CharField(default=None, max_length=1000, null=True)),
                ('info_contact_number', models.CharField(default=None, max_length=1000, null=True)),
                ('info_id', models.CharField(default=None, max_length=1000, null=True)),
                ('info_college', models.CharField(default=None, max_length=1000, null=True)),
                ('info_yrcourse', models.CharField(default=None, max_length=1000, null=True)),
                ('info_studentyear', models.CharField(default=None, max_length=1000, null=True)),
                ('info_gender', models.CharField(default=None, max_length=1000, null=True)),
                ('info_location', models.CharField(default=None, max_length=1000, null=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 15, 58, 23, 52238, tzinfo=utc))),
                ('imgpath', models.CharField(default='img/001.png', max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('birthday', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
