# Generated by Django 2.1.7 on 2019-03-24 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openapp', '0002_auto_20190324_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 9, 16, 59, 294014, tzinfo=utc))),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='anonuser',
            name='code',
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 9, 16, 59, 284012, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='AnonUser',
        ),
    ]
