# Generated by Django 2.1.7 on 2019-03-24 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0004_auto_20190324_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattrib',
            old_name='username',
            new_name='imgpath',
        ),
        migrations.RemoveField(
            model_name='userattrib',
            name='password',
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 9, 19, 34, 629922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 9, 19, 34, 629922, tzinfo=utc)),
        ),
    ]
