# Generated by Django 2.1.7 on 2019-04-06 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0008_auto_20190324_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='toUser',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='fromUser',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 16, 38, 7, 492671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 16, 38, 7, 493672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 16, 38, 7, 493672, tzinfo=utc)),
        ),
    ]
