# Generated by Django 2.1.7 on 2019-04-07 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0012_auto_20190407_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dateFrom',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dateTo',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 10, 33, 10, 82013, tzinfo=utc)),
        ),
    ]
