# Generated by Django 2.1.7 on 2019-04-07 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0017_auto_20190407_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 11, 29, 15, 469292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 11, 29, 15, 469292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='assignee',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 7, 11, 29, 15, 469292, tzinfo=utc)),
        ),
    ]
