# Generated by Django 2.1.7 on 2019-04-13 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0019_auto_20190413_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 9, 52, 38, 152602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 9, 52, 38, 154087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='assignee',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 9, 52, 38, 153083, tzinfo=utc)),
        ),
    ]
