# Generated by Django 2.1.7 on 2019-04-26 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openapp', '0025_auto_20190427_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(default=None, max_length=1000)),
                ('info_id', models.CharField(default=None, max_length=1000)),
                ('info_college', models.CharField(default=None, max_length=1000)),
                ('info_yrcourse', models.CharField(default=None, max_length=1000)),
                ('info_gender', models.CharField(default=None, max_length=1000)),
                ('info_location', models.CharField(default=None, max_length=1000)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openapp.Schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 18, 16, 50, 211401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 18, 16, 50, 211401, tzinfo=utc)),
        ),
    ]
