# Generated by Django 2.1.7 on 2019-05-01 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0029_auto_20190501_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='info_college',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='info_gender',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='info_id',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='info_location',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='info_name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='info_yrcourse',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 9, 15, 46, 792574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 9, 15, 46, 792574, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
