# Generated by Django 2.1.7 on 2019-05-04 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openapp', '0034_auto_20190504_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifType', models.CharField(default=None, max_length=1000, null=True)),
                ('notifId', models.CharField(default=None, max_length=1000, null=True)),
                ('status', models.CharField(default=None, max_length=1000, null=True)),
                ('message', models.CharField(default=None, max_length=1000, null=True)),
                ('destUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destUser', to=settings.AUTH_USER_MODEL)),
                ('sourceUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='approved',
            field=models.CharField(blank=True, default='NOT_APPROVED', max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 6, 36, 19, 685698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 6, 36, 19, 685698, tzinfo=utc)),
        ),
    ]
