# Generated by Django 2.1.7 on 2019-05-04 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0038_auto_20190504_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 14, 13, 32, 668658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 14, 13, 32, 668658, tzinfo=utc)),
        ),
    ]
