# Generated by Django 2.1.7 on 2019-05-04 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0039_auto_20190504_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.CharField(default='UNSEEN', max_length=1000),
        ),
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 14, 36, 18, 415904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 14, 36, 18, 415904, tzinfo=utc)),
        ),
    ]
